spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          batch_size: 300
        order_updates: true
        order_inserts: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}

  jwt:
    accessSecret: ${LOC_JWT_ACCESS_SECRET}
    refreshSecret: ${LOC_JWT_REFRESH_SECRET}
    accessTokenExpire: ${LOC_JWT_ACCESS_EXPIRE}
    refreshTokenExpire: ${LOC_JWT_REFRESH_EXPIRE}